Repository akveo/kittenTricks, pull requests merged in 2019-06, with the labels that each got.

#146 refactor(components): popover showcase refactor
  src/containers/components/popover/popover.container.tsx
  src/containers/components/popover/showcase/popoverContent.component.tsx
  src/containers/components/popover/showcase/popoverShowcase.component.tsx
  src/core/navigation/routes.tsx
Labels: needs review, next

#148 fix(auth): forms values applying fix
  src/components/auth/forgotPassword/forgotPasswordForm.component.tsx
  src/components/auth/signInForm1/signInForm1.component.tsx
  src/components/auth/signInForm2/signInForm2.component.tsx
  src/components/auth/signInForm3/signInForm3.component.tsx
  src/components/auth/signInForm4/signInForm4.component.tsx
  src/components/auth/signUpForm1/signUpForm1.component.tsx
  src/components/auth/signUpForm2/signUpForm2.component.tsx
Labels: needs review, next

#151 build(common): update eva dependencies
  package-lock.json
  package.json
  src/app.component.tsx
  src/containers/menu/themes/themes.container.tsx
  src/core/themes/index.ts
  src/core/themes/themeContext.ts
Labels: next

#154 fix(app): layouts/analytics/list-showcase
  package-lock.json
  src/components/common/layoutGridList/layoutGridList.component.tsx
  src/components/menu/layoutsList/layoutsList.component.tsx
  src/components/messaging/rightMessage.component.tsx
  src/containers/components/list/showcase/accessoryList.component.tsx
  src/containers/components/tooltip/showcase/bottomEndTooltip.component.tsx
  src/containers/menu/themes/themes.component.tsx
  src/core/utils/analytics.ts
Labels: needs review, next

#155 refactor(script): travis-ci scripts
  .travis.yml
  package.json
Labels: next

#156 fix(app): android status bar fix
  app.json
Labels: next

#157 build(common): update expo to sdk-33
  app.json
  babel.config.js
  config/dev.env.js
  config/prod.env.js
  metro.config.js
  package-lock.json
  package.json
  scripts/environment/set-env.sh
  src/app.component.tsx
  src/core/appLoader/applicationLoader.component.tsx
  tsconfig.json
Labels: next

#158 refactor(build): replace deprecated expo imports
  package.json
  src/containers/layouts/messaging/chat2/chat2.component.tsx
  src/containers/layouts/messaging/chat2/chat2.container.tsx
  src/containers/layouts/messaging/chat2/chat2FileSection.component.tsx
  src/containers/layouts/messaging/chat3/chat3.container.tsx
Labels: build, next

#160 build(common): update android package-name
  app.json
Labels: build, next

#161 release: v2.0.0
  config/prod.env.js
  package-lock.json
  package.json
  tsconfig.json
Labels: needs review, next

#163 build(common): bump react-native-ui-kitten version
  package-lock.json
  package.json
Labels: build

#172 fix(script): first-time start
  config/index.js
Labels: build

#186 fix(layout): bouncing preventing add
  src/components/common/scrollableAvoidKeyboard.component.tsx
Labels: enhancement

#177 docs(dev): add DEV_DOCS.md
  DEV_DOCS.md
Labels: documentation

#192 fix(navigation): navigation issues fix
  package-lock.json
  src/containers/layouts/articles/container/articles.container.tsx
  src/containers/layouts/auth/container/auth.container.tsx
  src/containers/layouts/auth/signIn1/signIn1.container.tsx
  src/containers/layouts/auth/signIn2/signIn2.container.tsx
  src/containers/layouts/auth/signIn3/signIn3.container.tsx
  src/containers/layouts/auth/signIn4/signIn4.container.tsx
  src/containers/layouts/auth/signIn5/signIn5.container.tsx
  src/containers/layouts/auth/signUp1/signUp1.container.tsx
  src/containers/layouts/auth/signUp2/signUp2.container.tsx
  src/containers/layouts/auth/signUp3/signUp3.container.tsx
  src/containers/layouts/auth/signUp4/signUp4.container.tsx
  src/containers/layouts/dashboards/container/dashboards.container.tsx
  src/containers/layouts/ecommerce/bookDetails/bookDetails.container.tsx
  src/containers/layouts/ecommerce/container/ecommerce.container.tsx
  src/containers/layouts/ecommerce/movieDetails/movieDetails.container.tsx
  src/containers/layouts/ecommerce/payment/payment.container.tsx
  src/containers/layouts/ecommerce/rentApartment/rentApartment.container.tsx
  src/containers/layouts/messaging/chat1/chat1.container.tsx
  src/containers/layouts/messaging/chat2/chat2.container.tsx
  src/containers/layouts/messaging/chat3/chat3.container.tsx
  src/containers/layouts/messaging/container/messaging.container.tsx
  src/containers/layouts/messaging/conversationsList/conversationsList.container.tsx
  src/containers/layouts/navigation/container/navigation.container.tsx
  src/containers/layouts/social/container/social.container.tsx
  src/containers/layouts/social/profile6/profile6.container.tsx
  src/containers/layouts/social/profile7/profile7.container.tsx
  src/containers/layouts/social/settings/settings.container.tsx
  src/containers/layouts/walkthrough/container/walkthrough.container.tsx
  src/containers/menu/components/components.container.tsx
  src/containers/menu/layouts/layouts.container.tsx
  src/containers/menu/menu.container.tsx
  src/core/navigation/actions.ts
  src/core/navigation/constants.ts
  src/core/navigation/index.ts
  src/core/navigation/options.tsx
  src/core/navigation/routes.tsx
  src/core/navigation/util.ts
Labels: needs review
